# Generated by Django 5.1 on 2024-08-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('pokemonId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
